from __future__ import annotations

import csv
import glob
import json
import logging
import os
import shutil
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .experiment_registry import ExperimentRegistry
from .job_queue import atomic_json_write, load_json, utc_now
from .settings import (
    BASE_DIR,
    COMPLETED_DIR,
    DEFAULT_EXPERIMENT_TIMEOUT_SECONDS,
    FAILED_DIR,
    LOG_DIR,
    PENDING_DIR,
    RUNNING_DIR,
    WORKER_POLL_SECONDS,
    validate_runtime,
)
from .telegram_api import TelegramAPI


def setup_logging() -> None:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
        handlers=[
            logging.FileHandler(
                LOG_DIR / "research_worker.log",
                encoding="utf-8",
            ),
            logging.StreamHandler(),
        ],
    )


def git_info() -> tuple[str, bool]:
    try:
        commit = subprocess.check_output(
            ["git", "rev-parse", "HEAD"],
            cwd=BASE_DIR,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()

        dirty = bool(
            subprocess.check_output(
                ["git", "status", "--porcelain"],
                cwd=BASE_DIR,
                text=True,
                stderr=subprocess.DEVNULL,
            ).strip()
        )
        return commit, dirty
    except Exception:
        return "unknown", True


def resolve_output_files(
    patterns: list[str],
    started_epoch: float,
) -> list[Path]:
    found: list[Path] = []

    for pattern in patterns:
        absolute = BASE_DIR / pattern
        for match in glob.glob(str(absolute)):
            path = Path(match)
            if not path.is_file():
                continue

            # Outputs generated by this run should be newer than the start.
            if path.stat().st_mtime >= started_epoch - 2:
                found.append(path)

    return sorted(
        set(found),
        key=lambda p: p.stat().st_mtime,
    )


class ResearchWorker:
    def __init__(self) -> None:
        self.registry = ExperimentRegistry()
        self.tg = TelegramAPI()

    def claim_job(self) -> Path | None:
        pending = sorted(
            PENDING_DIR.glob("*.json"),
            key=lambda p: p.stat().st_mtime,
        )

        for source in pending:
            target = RUNNING_DIR / source.name
            try:
                os.replace(source, target)
                return target
            except FileNotFoundError:
                continue

        return None

    def finish_job(
        self,
        running_path: Path,
        payload: dict[str, Any],
        success: bool,
    ) -> Path:
        destination_dir = COMPLETED_DIR if success else FAILED_DIR
        destination = destination_dir / running_path.name
        atomic_json_write(running_path, payload)
        os.replace(running_path, destination)
        return destination

    def run_job(self, running_path: Path) -> None:
        job = load_json(running_path)
        exp = self.registry.get(job["experiment_id"])

        started = time.time()
        started_at = utc_now()
        job["status"] = "running"
        job["started_at"] = started_at

        commit, dirty = git_info()
        job["git_commit"] = commit
        job["git_dirty_at_start"] = dirty

        log_path = LOG_DIR / f"{job['job_id']}.log"
        job["log_path"] = str(log_path)
        atomic_json_write(running_path, job)

        self.tg.send_message(
            f"🟡 STARTED {job['experiment_id']}\n"
            f"Job: {job['job_id']}\n"
            f"Git: {commit[:12] if commit != 'unknown' else commit}\n"
            f"Dirty working tree: {dirty}"
        )

        timeout_seconds = int(
            exp.get(
                "timeout_seconds",
                DEFAULT_EXPERIMENT_TIMEOUT_SECONDS,
            )
        )

        command = [str(x) for x in exp["command"]]
        env = os.environ.copy()
        env["RESEARCH_JOB_ID"] = job["job_id"]
        env["RESEARCH_EXPERIMENT_ID"] = job["experiment_id"]

        exit_code = None
        error_text = None

        try:
            with log_path.open(
                "w",
                encoding="utf-8",
                errors="replace",
            ) as log_handle:
                process = subprocess.run(
                    command,
                    cwd=BASE_DIR,
                    stdout=log_handle,
                    stderr=subprocess.STDOUT,
                    text=True,
                    env=env,
                    timeout=timeout_seconds,
                    check=False,
                )
                exit_code = int(process.returncode)

        except subprocess.TimeoutExpired:
            exit_code = 124
            error_text = (
                f"Experiment timed out after {timeout_seconds} seconds."
            )
            with log_path.open("a", encoding="utf-8") as log_handle:
                log_handle.write("\n" + error_text + "\n")

        except Exception as exc:
            exit_code = 125
            error_text = f"{type(exc).__name__}: {exc}"
            with log_path.open("a", encoding="utf-8") as log_handle:
                log_handle.write("\n" + error_text + "\n")

        outputs = resolve_output_files(
            exp.get("output_globs", []),
            started,
        )

        duration = round(time.time() - started, 2)
        success = exit_code == 0

        job.update(
            {
                "status": "completed" if success else "failed",
                "finished_at": utc_now(),
                "duration_seconds": duration,
                "exit_code": exit_code,
                "error": error_text,
                "output_paths": [
                    str(path.relative_to(BASE_DIR))
                    for path in outputs
                ],
            }
        )

        self.finish_job(
            running_path,
            job,
            success=success,
        )

        status_emoji = "🟢" if success else "🔴"
        lines = [
            f"{status_emoji} {job['experiment_id']} "
            f"{'COMPLETED' if success else 'FAILED'}",
            f"Duration: {duration} s",
        ]

        if success:
            lines.extend(
                [
                    "",
                    "Results saved on the server.",
                ]
            )
        elif error_text:
            lines.extend(
                [
                    "",
                    f"Error: {error_text}",
                    f"Use /logs {job['experiment_id']} for details.",
                ]
            )

        self.tg.send_message("\n".join(lines))

    def run(self) -> None:
        self.tg.send_message(
            "Research worker is online."
        )

        while True:
            try:
                path = self.claim_job()
                if path is None:
                    time.sleep(WORKER_POLL_SECONDS)
                    continue

                self.run_job(path)

            except KeyboardInterrupt:
                raise
            except Exception:
                logging.exception("Worker loop error")
                time.sleep(5)


def main() -> None:
    validate_runtime()
    setup_logging()
    ResearchWorker().run()


if __name__ == "__main__":
    main()
