from __future__ import annotations

import json
import logging
import time
from pathlib import Path

from .ai_queue import AIJobQueue
from .experiment_registry import ExperimentRegistry
from .job_queue import JobQueue
from .proposal_manager import ProposalManager
from .settings import (
    LOG_DIR,
    STATE_DIR,
    TELEGRAM_CHAT_ID,
    TELEGRAM_POLL_TIMEOUT,
    validate_runtime,
)
from .telegram_api import TelegramAPI


HELP_TEXT = """Research Automation — Stage 2

AI research:
/propose <research request>
/proposals
/proposal P-...
/diff P-...
/promote P-...

Frozen experiments:
/experiments
/run E-0001
/result E-0001

General:
/status
/current
/logs <E-... or P-...>
/help

Code proposals use isolated Git worktrees.
Nothing generated by AI is executed before your approval.
No CSV files are sent to Telegram.
"""


def setup_logging() -> None:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
        handlers=[
            logging.FileHandler(
                LOG_DIR / "telegram_bot.log",
                encoding="utf-8",
            ),
            logging.StreamHandler(),
        ],
    )


def read_json_if_exists(path: Path):
    if not path.exists():
        return None
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def compact_json(value) -> str:
    return json.dumps(
        value,
        indent=2,
        ensure_ascii=False,
    )


def approval_keyboard(experiment_id: str) -> str:
    return json.dumps(
        {
            "inline_keyboard": [
                [
                    {
                        "text": "✅ APPROVE",
                        "callback_data": f"approve:{experiment_id}",
                    },
                    {
                        "text": "❌ REJECT",
                        "callback_data": f"reject:{experiment_id}",
                    },
                ]
            ]
        },
        ensure_ascii=False,
    )


def ai_proposal_keyboard(proposal_id: str) -> str:
    return json.dumps(
        {
            "inline_keyboard": [
                [
                    {
                        "text": "🧾 VIEW DIFF",
                        "callback_data": f"ai_diff:{proposal_id}",
                    }
                ],
                [
                    {
                        "text": "✅ APPROVE CODE",
                        "callback_data": f"ai_approve:{proposal_id}",
                    },
                    {
                        "text": "❌ REJECT",
                        "callback_data": f"ai_reject:{proposal_id}",
                    },
                ],
            ]
        },
        ensure_ascii=False,
    )


def tail(path: Path, lines: int = 60) -> str:
    if not path.exists():
        return "Log file not found."
    with path.open(
        "r",
        encoding="utf-8",
        errors="replace",
    ) as handle:
        content = handle.readlines()
    return "".join(content[-lines:])


class ResearchBot:
    def __init__(self) -> None:
        self.tg = TelegramAPI()
        self.registry = ExperimentRegistry()
        self.queue = JobQueue()
        self.ai_queue = AIJobQueue()
        self.proposals = ProposalManager()

    def authorized(self, message: dict) -> bool:
        chat_id = str(
            message.get("chat", {}).get("id", "")
        )
        return chat_id == str(TELEGRAM_CHAT_ID)

    def reply(
        self,
        text: str,
        reply_markup: str | None = None,
    ) -> None:
        self.tg.send_message(
            text,
            reply_markup=reply_markup,
        )

    def _stage1_result(self, argument: str) -> str:
        found = self.queue.latest_job(argument)
        if not found:
            return f"No job found for {argument}."

        status, job = found
        lines = [
            f"{argument} — {status.upper()}",
            f"Duration: {job.get('duration_seconds', '-')} s",
        ]

        if status == "failed" and job.get("error"):
            lines.extend(
                ["", f"Error: {job['error']}"]
            )

        return "\n".join(lines)

    def _proposal_result(self, pid: str) -> str:
        proposal = self.proposals.get(pid)
        lines = [
            f"{pid} — {proposal.get('status', '-').upper()}",
            proposal.get("title", "-"),
        ]

        analysis = proposal.get("analysis") or {}
        verdict = analysis.get("verdict")
        if verdict:
            lines.extend(
                [
                    "",
                    f"AI verdict: {verdict}",
                ]
            )

        text = str(
            analysis.get("telegram_text", "")
        ).strip()
        if text:
            lines.extend(["", text])

        return "\n".join(lines)

    def _send_proposal_diff(self, pid: str) -> None:
        proposal = self.proposals.get(pid)
        diff_path = Path(
            proposal.get("diff_path", "")
        )

        if not diff_path.exists():
            self.reply(
                f"No diff found for {pid}."
            )
            return

        diff = diff_path.read_text(
            encoding="utf-8",
            errors="replace",
        )

        max_chars = 24_000
        if len(diff) > max_chars:
            diff = (
                diff[:max_chars]
                + "\n\n[Diff truncated in Telegram. "
                "Full diff remains on server.]"
            )

        self.reply(
            f"{pid}\n"
            f"{proposal.get('diff_stat', '')}\n\n"
            f"{diff}"
        )

    def _queue_ai_execution(
        self,
        pid: str,
        sender: str,
    ) -> None:
        proposal = self.proposals.get(pid)

        if proposal.get("status") != "ready_for_approval":
            raise RuntimeError(
                f"{pid} is not awaiting approval. "
                f"Current status: {proposal.get('status')}"
            )

        self.proposals.update(
            pid,
            status="approved",
            approved_by=sender,
        )

        job = self.ai_queue.create(
            "execute_proposal",
            requested_by=sender,
            proposal_id=pid,
        )

        self.reply(
            f"✅ {pid} approved.\n"
            f"Execution queued."
        )

    def handle(self, message: dict) -> None:
        if not self.authorized(message):
            logging.warning(
                "Rejected unauthorized Telegram message from chat_id=%s",
                message.get("chat", {}).get("id"),
            )
            return

        text = str(message.get("text", "")).strip()
        sender = str(
            message.get("from", {}).get("id", "unknown")
        )

        if not text.startswith("/"):
            self.reply(
                "Use /propose <research request> or /help."
            )
            return

        parts = text.split()
        command = parts[0].split("@", 1)[0].lower()
        argument = parts[1].upper() if len(parts) > 1 else ""

        try:
            if command in {"/start", "/help"}:
                self.reply(HELP_TEXT)
                return

            if command == "/status":
                stage1 = self.queue.queue_status()
                ai = self.ai_queue.status()
                self.reply(
                    "Research status\n"
                    f"Experiments: "
                    f"{stage1['pending']} pending / "
                    f"{stage1['running']} running\n"
                    f"AI: "
                    f"{ai['pending']} pending / "
                    f"{ai['running']} running"
                )
                return

            if command == "/experiments":
                experiments = self.registry.all()
                lines = ["Frozen experiments:"]
                for exp in experiments:
                    lines.append(
                        f"{exp['experiment_id']} — {exp['title']}"
                    )
                self.reply("\n".join(lines))
                return

            if command == "/current":
                current = read_json_if_exists(
                    STATE_DIR / "current_strategy.json"
                )
                frozen = read_json_if_exists(
                    STATE_DIR / "frozen_rules.json"
                )
                self.reply(
                    "CURRENT STRATEGY\n"
                    + compact_json(current or {})
                    + "\n\nFROZEN RULES\n"
                    + compact_json(frozen or {})
                )
                return

            if command == "/propose":
                request_text = text[len(parts[0]):].strip()
                if not request_text:
                    self.reply(
                        "Usage:\n"
                        "/propose <research request>"
                    )
                    return

                job = self.ai_queue.create(
                    "generate_proposal",
                    requested_by=sender,
                    request_text=request_text,
                )

                self.reply(
                    "🧠 Research request queued."
                )
                return

            if command == "/proposals":
                proposals = self.proposals.latest(10)
                if not proposals:
                    self.reply("No AI proposals yet.")
                    return

                lines = ["Latest AI proposals:"]
                for proposal in proposals:
                    lines.append(
                        f"{proposal.get('proposal_id')} — "
                        f"{proposal.get('status')} — "
                        f"{proposal.get('title')}"
                    )
                self.reply("\n".join(lines))
                return

            if command == "/proposal":
                if not argument:
                    self.reply("Usage: /proposal P-...")
                    return

                proposal = self.proposals.get(argument)
                markup = None
                if proposal.get("status") == "ready_for_approval":
                    markup = ai_proposal_keyboard(argument)

                self.reply(
                    self._proposal_result(argument),
                    reply_markup=markup,
                )
                return

            if command == "/diff":
                if not argument:
                    self.reply("Usage: /diff P-...")
                    return

                self._send_proposal_diff(argument)
                return

            if command == "/promote":
                if not argument:
                    self.reply("Usage: /promote P-...")
                    return

                self.ai_queue.create(
                    "promote_proposal",
                    requested_by=sender,
                    proposal_id=argument,
                )
                self.reply(
                    f"🚀 {argument} promotion queued."
                )
                return

            if command == "/run":
                if not argument:
                    self.reply("Usage: /run E-0001")
                    return

                exp = self.registry.get(argument)
                self.queue.create_proposal(
                    exp,
                    requested_by=sender,
                )

                self.reply(
                    self.registry.proposal_text(exp),
                    reply_markup=approval_keyboard(
                        exp["experiment_id"]
                    ),
                )
                return

            if command == "/approve":
                if not argument:
                    self.reply(
                        "Usage: /approve E-0001 or /approve P-..."
                    )
                    return

                if argument.startswith("P-"):
                    self._queue_ai_execution(
                        argument,
                        sender,
                    )
                    return

                exp = self.registry.get(argument)
                job = self.queue.approve_proposal(
                    exp,
                    approved_by=sender,
                )
                self.reply(
                    f"✅ {argument} approved.\n"
                    f"Execution queued."
                )
                return

            if command == "/reject":
                if not argument:
                    self.reply(
                        "Usage: /reject E-0001 or /reject P-..."
                    )
                    return

                if argument.startswith("P-"):
                    self.proposals.update(
                        argument,
                        status="rejected",
                        rejected_by=sender,
                    )
                    self.reply(
                        f"❌ {argument} rejected."
                    )
                    return

                ok = self.queue.reject_proposal(argument)
                self.reply(
                    f"{argument}: "
                    + (
                        "proposal rejected."
                        if ok
                        else "no pending proposal."
                    )
                )
                return

            if command == "/result":
                if not argument:
                    self.reply(
                        "Usage: /result E-0001 or /result P-..."
                    )
                    return

                if argument.startswith("P-"):
                    self.reply(
                        self._proposal_result(argument)
                    )
                else:
                    self.reply(
                        self._stage1_result(argument)
                    )
                return

            if command == "/logs":
                if not argument:
                    self.reply(
                        "Usage: /logs E-0001 or /logs P-..."
                    )
                    return

                if argument.startswith("P-"):
                    proposal = self.proposals.get(argument)
                    log_path = Path(
                        proposal.get("log_path", "")
                    )
                else:
                    found = self.queue.latest_job(argument)
                    if not found:
                        self.reply(
                            f"No job found for {argument}."
                        )
                        return
                    _, job = found
                    log_path = Path(
                        job.get("log_path", "")
                    )

                self.reply(
                    f"Last log lines for {argument}\n\n"
                    + tail(log_path, 60)
                )
                return

            self.reply("Unknown command. Use /help.")

        except Exception as exc:
            logging.exception("Command failed")
            self.reply(
                f"Command failed:\n"
                f"{type(exc).__name__}: {exc}"
            )

    def handle_callback(self, callback: dict) -> None:
        message = callback.get("message", {})
        if not self.authorized(message):
            logging.warning(
                "Rejected unauthorized callback from chat_id=%s",
                message.get("chat", {}).get("id"),
            )
            return

        callback_id = str(callback.get("id", ""))
        data = str(callback.get("data", ""))
        sender = str(
            callback.get("from", {}).get("id", "unknown")
        )

        try:
            action, item_id = data.split(":", 1)
            item_id = item_id.upper()

            if action == "approve":
                exp = self.registry.get(item_id)
                self.queue.approve_proposal(
                    exp,
                    approved_by=sender,
                )
                self.tg.answer_callback_query(
                    callback_id,
                    "Experiment approved",
                )
                self.reply(
                    f"✅ {item_id} approved.\n"
                    f"Execution queued."
                )
                return

            if action == "reject":
                ok = self.queue.reject_proposal(
                    item_id
                )
                self.tg.answer_callback_query(
                    callback_id,
                    "Experiment rejected",
                )
                self.reply(
                    f"❌ {item_id}: "
                    + (
                        "proposal rejected."
                        if ok
                        else "no pending proposal."
                    )
                )
                return

            if action == "ai_diff":
                self.tg.answer_callback_query(
                    callback_id,
                    "Showing code diff",
                )
                self._send_proposal_diff(item_id)
                return

            if action == "ai_approve":
                self._queue_ai_execution(
                    item_id,
                    sender,
                )
                self.tg.answer_callback_query(
                    callback_id,
                    "Code approved",
                )
                return

            if action == "ai_reject":
                self.proposals.update(
                    item_id,
                    status="rejected",
                    rejected_by=sender,
                )
                self.tg.answer_callback_query(
                    callback_id,
                    "Proposal rejected",
                )
                self.reply(
                    f"❌ {item_id} rejected."
                )
                return

            if action == "ai_promote":
                self.ai_queue.create(
                    "promote_proposal",
                    requested_by=sender,
                    proposal_id=item_id,
                )
                self.tg.answer_callback_query(
                    callback_id,
                    "Promotion queued",
                )
                self.reply(
                    f"🚀 {item_id} promotion queued."
                )
                return

            if action == "ai_keep":
                self.proposals.update(
                    item_id,
                    status="kept_branch",
                )
                self.tg.answer_callback_query(
                    callback_id,
                    "Branch kept",
                )
                self.reply(
                    f"📌 {item_id} kept on its research branch."
                )
                return

            if action == "ai_next":
                proposal = self.proposals.get(item_id)
                analysis = proposal.get("analysis") or {}
                next_request = str(
                    analysis.get("next_request", "")
                ).strip()

                if not next_request:
                    raise RuntimeError(
                        "No next experiment was proposed."
                    )

                self.ai_queue.create(
                    "generate_proposal",
                    requested_by=sender,
                    request_text=next_request,
                    parent_proposal_id=item_id,
                )
                self.tg.answer_callback_query(
                    callback_id,
                    "Next proposal queued",
                )
                self.reply(
                    "🧪 Next research proposal queued."
                )
                return

            self.tg.answer_callback_query(
                callback_id,
                "Unknown action",
            )

        except Exception as exc:
            logging.exception("Callback failed")
            try:
                self.tg.answer_callback_query(
                    callback_id,
                    "Action failed",
                )
            except Exception:
                pass

            self.reply(
                f"Action failed:\n"
                f"{type(exc).__name__}: {exc}"
            )

    def run(self) -> None:
        offset = None
        self.reply(
            "Research Automation Stage 2 is online.\n"
            "Use /help."
        )

        while True:
            try:
                updates = self.tg.get_updates(
                    offset=offset,
                    timeout=TELEGRAM_POLL_TIMEOUT,
                )

                for update in updates:
                    offset = int(
                        update["update_id"]
                    ) + 1

                    callback = update.get(
                        "callback_query"
                    )
                    if callback:
                        self.handle_callback(
                            callback
                        )
                        continue

                    message = update.get("message")
                    if message:
                        self.handle(message)

            except KeyboardInterrupt:
                raise
            except Exception:
                logging.exception(
                    "Telegram polling error"
                )
                time.sleep(5)


def main() -> None:
    validate_runtime()
    setup_logging()
    ResearchBot().run()


if __name__ == "__main__":
    main()
